// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Building_Level.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Deploy {

  /// <summary>Holder for reflection information generated from Building_Level.proto</summary>
  public static partial class BuildingLevelReflection {

    #region Descriptor
    /// <summary>File descriptor for Building_Level.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BuildingLevelReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRCdWlsZGluZ19MZXZlbC5wcm90bxIGZGVwbG95IncKDkJ1aWxkaW5nX0xl",
            "dmVsEgoKAklkGAEgASgFEg8KB0J1aWxkSWQYAiABKAUSEgoKQnVpbGRMZXZl",
            "bBgDIAEoBRIaChJCdWlsZGluZ1NjYWxlVmFsdWUYBCABKAUSGAoQVXNhYmxl",
            "QXJlYUlkTGlzdBgFIAMoBSKQAQoSQnVpbGRpbmdfTGV2ZWxfTWFwEjQKBUl0",
            "ZW1zGAEgAygLMiUuZGVwbG95LkJ1aWxkaW5nX0xldmVsX01hcC5JdGVtc0Vu",
            "dHJ5GkQKCkl0ZW1zRW50cnkSCwoDa2V5GAEgASgFEiUKBXZhbHVlGAIgASgL",
            "MhYuZGVwbG95LkJ1aWxkaW5nX0xldmVsOgI4AWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Deploy.Building_Level), global::Deploy.Building_Level.Parser, new[]{ "Id", "BuildId", "BuildLevel", "BuildingScaleValue", "UsableAreaIdList" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Deploy.Building_Level_Map), global::Deploy.Building_Level_Map.Parser, new[]{ "Items" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Building_Level : pb::IMessage<Building_Level> {
    private static readonly pb::MessageParser<Building_Level> _parser = new pb::MessageParser<Building_Level>(() => new Building_Level());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Building_Level> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Deploy.BuildingLevelReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Building_Level() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Building_Level(Building_Level other) : this() {
      id_ = other.id_;
      buildId_ = other.buildId_;
      buildLevel_ = other.buildLevel_;
      buildingScaleValue_ = other.buildingScaleValue_;
      usableAreaIdList_ = other.usableAreaIdList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Building_Level Clone() {
      return new Building_Level(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "BuildId" field.</summary>
    public const int BuildIdFieldNumber = 2;
    private int buildId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BuildId {
      get { return buildId_; }
      set {
        buildId_ = value;
      }
    }

    /// <summary>Field number for the "BuildLevel" field.</summary>
    public const int BuildLevelFieldNumber = 3;
    private int buildLevel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BuildLevel {
      get { return buildLevel_; }
      set {
        buildLevel_ = value;
      }
    }

    /// <summary>Field number for the "BuildingScaleValue" field.</summary>
    public const int BuildingScaleValueFieldNumber = 4;
    private int buildingScaleValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BuildingScaleValue {
      get { return buildingScaleValue_; }
      set {
        buildingScaleValue_ = value;
      }
    }

    /// <summary>Field number for the "UsableAreaIdList" field.</summary>
    public const int UsableAreaIdListFieldNumber = 5;
    private static readonly pb::FieldCodec<int> _repeated_usableAreaIdList_codec
        = pb::FieldCodec.ForInt32(42);
    private readonly pbc::RepeatedField<int> usableAreaIdList_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> UsableAreaIdList {
      get { return usableAreaIdList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Building_Level);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Building_Level other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (BuildId != other.BuildId) return false;
      if (BuildLevel != other.BuildLevel) return false;
      if (BuildingScaleValue != other.BuildingScaleValue) return false;
      if(!usableAreaIdList_.Equals(other.usableAreaIdList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (BuildId != 0) hash ^= BuildId.GetHashCode();
      if (BuildLevel != 0) hash ^= BuildLevel.GetHashCode();
      if (BuildingScaleValue != 0) hash ^= BuildingScaleValue.GetHashCode();
      hash ^= usableAreaIdList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (BuildId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(BuildId);
      }
      if (BuildLevel != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(BuildLevel);
      }
      if (BuildingScaleValue != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(BuildingScaleValue);
      }
      usableAreaIdList_.WriteTo(output, _repeated_usableAreaIdList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (BuildId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BuildId);
      }
      if (BuildLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BuildLevel);
      }
      if (BuildingScaleValue != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BuildingScaleValue);
      }
      size += usableAreaIdList_.CalculateSize(_repeated_usableAreaIdList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Building_Level other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.BuildId != 0) {
        BuildId = other.BuildId;
      }
      if (other.BuildLevel != 0) {
        BuildLevel = other.BuildLevel;
      }
      if (other.BuildingScaleValue != 0) {
        BuildingScaleValue = other.BuildingScaleValue;
      }
      usableAreaIdList_.Add(other.usableAreaIdList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            BuildId = input.ReadInt32();
            break;
          }
          case 24: {
            BuildLevel = input.ReadInt32();
            break;
          }
          case 32: {
            BuildingScaleValue = input.ReadInt32();
            break;
          }
          case 42:
          case 40: {
            usableAreaIdList_.AddEntriesFrom(input, _repeated_usableAreaIdList_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Building_Level_Map : pb::IMessage<Building_Level_Map> {
    private static readonly pb::MessageParser<Building_Level_Map> _parser = new pb::MessageParser<Building_Level_Map>(() => new Building_Level_Map());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Building_Level_Map> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Deploy.BuildingLevelReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Building_Level_Map() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Building_Level_Map(Building_Level_Map other) : this() {
      items_ = other.items_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Building_Level_Map Clone() {
      return new Building_Level_Map(this);
    }

    /// <summary>Field number for the "Items" field.</summary>
    public const int ItemsFieldNumber = 1;
    private static readonly pbc::MapField<int, global::Deploy.Building_Level>.Codec _map_items_codec
        = new pbc::MapField<int, global::Deploy.Building_Level>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Deploy.Building_Level.Parser), 10);
    private readonly pbc::MapField<int, global::Deploy.Building_Level> items_ = new pbc::MapField<int, global::Deploy.Building_Level>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, global::Deploy.Building_Level> Items {
      get { return items_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Building_Level_Map);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Building_Level_Map other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!Items.Equals(other.Items)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= Items.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      items_.WriteTo(output, _map_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += items_.CalculateSize(_map_items_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Building_Level_Map other) {
      if (other == null) {
        return;
      }
      items_.Add(other.items_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            items_.AddEntriesFrom(input, _map_items_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
