// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Building_Config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Deploy {

  /// <summary>Holder for reflection information generated from Building_Config.proto</summary>
  public static partial class BuildingConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for Building_Config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BuildingConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVCdWlsZGluZ19Db25maWcucHJvdG8SBmRlcGxveSKBAQoPQnVpbGRpbmdf",
            "Q29uZmlnEgoKAklkGAEgASgFEgwKBE5hbWUYAiABKAkSDwoHU2V0VHlwZRgD",
            "IAEoBRIVCg1HcmlkSXRlbVNpemVYGAQgASgFEhUKDUdyaWRJdGVtU2l6ZVkY",
            "BSABKAUSFQoNR3JpZEl0ZW1TaXplWhgGIAEoBSKTAQoTQnVpbGRpbmdfQ29u",
            "ZmlnX01hcBI1CgVJdGVtcxgBIAMoCzImLmRlcGxveS5CdWlsZGluZ19Db25m",
            "aWdfTWFwLkl0ZW1zRW50cnkaRQoKSXRlbXNFbnRyeRILCgNrZXkYASABKAUS",
            "JgoFdmFsdWUYAiABKAsyFy5kZXBsb3kuQnVpbGRpbmdfQ29uZmlnOgI4AWIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Deploy.Building_Config), global::Deploy.Building_Config.Parser, new[]{ "Id", "Name", "SetType", "GridItemSizeX", "GridItemSizeY", "GridItemSizeZ" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Deploy.Building_Config_Map), global::Deploy.Building_Config_Map.Parser, new[]{ "Items" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Building_Config : pb::IMessage<Building_Config> {
    private static readonly pb::MessageParser<Building_Config> _parser = new pb::MessageParser<Building_Config>(() => new Building_Config());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Building_Config> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Deploy.BuildingConfigReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Building_Config() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Building_Config(Building_Config other) : this() {
      id_ = other.id_;
      name_ = other.name_;
      setType_ = other.setType_;
      gridItemSizeX_ = other.gridItemSizeX_;
      gridItemSizeY_ = other.gridItemSizeY_;
      gridItemSizeZ_ = other.gridItemSizeZ_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Building_Config Clone() {
      return new Building_Config(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SetType" field.</summary>
    public const int SetTypeFieldNumber = 3;
    private int setType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SetType {
      get { return setType_; }
      set {
        setType_ = value;
      }
    }

    /// <summary>Field number for the "GridItemSizeX" field.</summary>
    public const int GridItemSizeXFieldNumber = 4;
    private int gridItemSizeX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GridItemSizeX {
      get { return gridItemSizeX_; }
      set {
        gridItemSizeX_ = value;
      }
    }

    /// <summary>Field number for the "GridItemSizeY" field.</summary>
    public const int GridItemSizeYFieldNumber = 5;
    private int gridItemSizeY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GridItemSizeY {
      get { return gridItemSizeY_; }
      set {
        gridItemSizeY_ = value;
      }
    }

    /// <summary>Field number for the "GridItemSizeZ" field.</summary>
    public const int GridItemSizeZFieldNumber = 6;
    private int gridItemSizeZ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GridItemSizeZ {
      get { return gridItemSizeZ_; }
      set {
        gridItemSizeZ_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Building_Config);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Building_Config other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (SetType != other.SetType) return false;
      if (GridItemSizeX != other.GridItemSizeX) return false;
      if (GridItemSizeY != other.GridItemSizeY) return false;
      if (GridItemSizeZ != other.GridItemSizeZ) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (SetType != 0) hash ^= SetType.GetHashCode();
      if (GridItemSizeX != 0) hash ^= GridItemSizeX.GetHashCode();
      if (GridItemSizeY != 0) hash ^= GridItemSizeY.GetHashCode();
      if (GridItemSizeZ != 0) hash ^= GridItemSizeZ.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (SetType != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(SetType);
      }
      if (GridItemSizeX != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(GridItemSizeX);
      }
      if (GridItemSizeY != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(GridItemSizeY);
      }
      if (GridItemSizeZ != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(GridItemSizeZ);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (SetType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SetType);
      }
      if (GridItemSizeX != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GridItemSizeX);
      }
      if (GridItemSizeY != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GridItemSizeY);
      }
      if (GridItemSizeZ != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GridItemSizeZ);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Building_Config other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.SetType != 0) {
        SetType = other.SetType;
      }
      if (other.GridItemSizeX != 0) {
        GridItemSizeX = other.GridItemSizeX;
      }
      if (other.GridItemSizeY != 0) {
        GridItemSizeY = other.GridItemSizeY;
      }
      if (other.GridItemSizeZ != 0) {
        GridItemSizeZ = other.GridItemSizeZ;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            SetType = input.ReadInt32();
            break;
          }
          case 32: {
            GridItemSizeX = input.ReadInt32();
            break;
          }
          case 40: {
            GridItemSizeY = input.ReadInt32();
            break;
          }
          case 48: {
            GridItemSizeZ = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Building_Config_Map : pb::IMessage<Building_Config_Map> {
    private static readonly pb::MessageParser<Building_Config_Map> _parser = new pb::MessageParser<Building_Config_Map>(() => new Building_Config_Map());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Building_Config_Map> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Deploy.BuildingConfigReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Building_Config_Map() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Building_Config_Map(Building_Config_Map other) : this() {
      items_ = other.items_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Building_Config_Map Clone() {
      return new Building_Config_Map(this);
    }

    /// <summary>Field number for the "Items" field.</summary>
    public const int ItemsFieldNumber = 1;
    private static readonly pbc::MapField<int, global::Deploy.Building_Config>.Codec _map_items_codec
        = new pbc::MapField<int, global::Deploy.Building_Config>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Deploy.Building_Config.Parser), 10);
    private readonly pbc::MapField<int, global::Deploy.Building_Config> items_ = new pbc::MapField<int, global::Deploy.Building_Config>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, global::Deploy.Building_Config> Items {
      get { return items_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Building_Config_Map);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Building_Config_Map other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!Items.Equals(other.Items)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= Items.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      items_.WriteTo(output, _map_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += items_.CalculateSize(_map_items_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Building_Config_Map other) {
      if (other == null) {
        return;
      }
      items_.Add(other.items_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            items_.AddEntriesFrom(input, _map_items_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
