// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Guild_Rank.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Deploy {

  /// <summary>Holder for reflection information generated from Guild_Rank.proto</summary>
  public static partial class GuildRankReflection {

    #region Descriptor
    /// <summary>File descriptor for Guild_Rank.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GuildRankReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBHdWlsZF9SYW5rLnByb3RvEgZkZXBsb3kinQMKCkd1aWxkX1JhbmsSCgoC",
            "SWQYASABKAUSDAoETmFtZRgCIAEoCRIhChlCdWlsZGluZ1NjYWxlVmFsdWVS",
            "ZXF1aXJlGAMgASgFEhwKFEZhY2lsaXR5VmFsdWVSZXF1aXJlGAQgASgFEhsK",
            "E0VudHJ1c3RTY29yZVJlcXVpcmUYBSABKAUSRgoSVmVudHVyZXJSYW5rV2Vp",
            "Z2h0GAYgAygLMiouZGVwbG95Lkd1aWxkX1JhbmsuVmVudHVyZXJSYW5rV2Vp",
            "Z2h0RW50cnkSFAoMRW50cnVzdENvdW50GAcgASgFEkQKEUVudHJ1c3RSYW5r",
            "V2VpZ2h0GAggAygLMikuZGVwbG95Lkd1aWxkX1JhbmsuRW50cnVzdFJhbmtX",
            "ZWlnaHRFbnRyeRo5ChdWZW50dXJlclJhbmtXZWlnaHRFbnRyeRILCgNrZXkY",
            "ASABKAUSDQoFdmFsdWUYAiABKAU6AjgBGjgKFkVudHJ1c3RSYW5rV2VpZ2h0",
            "RW50cnkSCwoDa2V5GAEgASgFEg0KBXZhbHVlGAIgASgFOgI4ASKEAQoOR3Vp",
            "bGRfUmFua19NYXASMAoFSXRlbXMYASADKAsyIS5kZXBsb3kuR3VpbGRfUmFu",
            "a19NYXAuSXRlbXNFbnRyeRpACgpJdGVtc0VudHJ5EgsKA2tleRgBIAEoBRIh",
            "CgV2YWx1ZRgCIAEoCzISLmRlcGxveS5HdWlsZF9SYW5rOgI4AWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Deploy.Guild_Rank), global::Deploy.Guild_Rank.Parser, new[]{ "Id", "Name", "BuildingScaleValueRequire", "FacilityValueRequire", "EntrustScoreRequire", "VenturerRankWeight", "EntrustCount", "EntrustRankWeight" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Deploy.Guild_Rank_Map), global::Deploy.Guild_Rank_Map.Parser, new[]{ "Items" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Guild_Rank : pb::IMessage<Guild_Rank> {
    private static readonly pb::MessageParser<Guild_Rank> _parser = new pb::MessageParser<Guild_Rank>(() => new Guild_Rank());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Guild_Rank> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Deploy.GuildRankReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Guild_Rank() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Guild_Rank(Guild_Rank other) : this() {
      id_ = other.id_;
      name_ = other.name_;
      buildingScaleValueRequire_ = other.buildingScaleValueRequire_;
      facilityValueRequire_ = other.facilityValueRequire_;
      entrustScoreRequire_ = other.entrustScoreRequire_;
      venturerRankWeight_ = other.venturerRankWeight_.Clone();
      entrustCount_ = other.entrustCount_;
      entrustRankWeight_ = other.entrustRankWeight_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Guild_Rank Clone() {
      return new Guild_Rank(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "BuildingScaleValueRequire" field.</summary>
    public const int BuildingScaleValueRequireFieldNumber = 3;
    private int buildingScaleValueRequire_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BuildingScaleValueRequire {
      get { return buildingScaleValueRequire_; }
      set {
        buildingScaleValueRequire_ = value;
      }
    }

    /// <summary>Field number for the "FacilityValueRequire" field.</summary>
    public const int FacilityValueRequireFieldNumber = 4;
    private int facilityValueRequire_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int FacilityValueRequire {
      get { return facilityValueRequire_; }
      set {
        facilityValueRequire_ = value;
      }
    }

    /// <summary>Field number for the "EntrustScoreRequire" field.</summary>
    public const int EntrustScoreRequireFieldNumber = 5;
    private int entrustScoreRequire_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int EntrustScoreRequire {
      get { return entrustScoreRequire_; }
      set {
        entrustScoreRequire_ = value;
      }
    }

    /// <summary>Field number for the "VenturerRankWeight" field.</summary>
    public const int VenturerRankWeightFieldNumber = 6;
    private static readonly pbc::MapField<int, int>.Codec _map_venturerRankWeight_codec
        = new pbc::MapField<int, int>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForInt32(16, 0), 50);
    private readonly pbc::MapField<int, int> venturerRankWeight_ = new pbc::MapField<int, int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, int> VenturerRankWeight {
      get { return venturerRankWeight_; }
    }

    /// <summary>Field number for the "EntrustCount" field.</summary>
    public const int EntrustCountFieldNumber = 7;
    private int entrustCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int EntrustCount {
      get { return entrustCount_; }
      set {
        entrustCount_ = value;
      }
    }

    /// <summary>Field number for the "EntrustRankWeight" field.</summary>
    public const int EntrustRankWeightFieldNumber = 8;
    private static readonly pbc::MapField<int, int>.Codec _map_entrustRankWeight_codec
        = new pbc::MapField<int, int>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForInt32(16, 0), 66);
    private readonly pbc::MapField<int, int> entrustRankWeight_ = new pbc::MapField<int, int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, int> EntrustRankWeight {
      get { return entrustRankWeight_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Guild_Rank);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Guild_Rank other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (BuildingScaleValueRequire != other.BuildingScaleValueRequire) return false;
      if (FacilityValueRequire != other.FacilityValueRequire) return false;
      if (EntrustScoreRequire != other.EntrustScoreRequire) return false;
      if (!VenturerRankWeight.Equals(other.VenturerRankWeight)) return false;
      if (EntrustCount != other.EntrustCount) return false;
      if (!EntrustRankWeight.Equals(other.EntrustRankWeight)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (BuildingScaleValueRequire != 0) hash ^= BuildingScaleValueRequire.GetHashCode();
      if (FacilityValueRequire != 0) hash ^= FacilityValueRequire.GetHashCode();
      if (EntrustScoreRequire != 0) hash ^= EntrustScoreRequire.GetHashCode();
      hash ^= VenturerRankWeight.GetHashCode();
      if (EntrustCount != 0) hash ^= EntrustCount.GetHashCode();
      hash ^= EntrustRankWeight.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (BuildingScaleValueRequire != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(BuildingScaleValueRequire);
      }
      if (FacilityValueRequire != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(FacilityValueRequire);
      }
      if (EntrustScoreRequire != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(EntrustScoreRequire);
      }
      venturerRankWeight_.WriteTo(output, _map_venturerRankWeight_codec);
      if (EntrustCount != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(EntrustCount);
      }
      entrustRankWeight_.WriteTo(output, _map_entrustRankWeight_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (BuildingScaleValueRequire != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BuildingScaleValueRequire);
      }
      if (FacilityValueRequire != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FacilityValueRequire);
      }
      if (EntrustScoreRequire != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EntrustScoreRequire);
      }
      size += venturerRankWeight_.CalculateSize(_map_venturerRankWeight_codec);
      if (EntrustCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EntrustCount);
      }
      size += entrustRankWeight_.CalculateSize(_map_entrustRankWeight_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Guild_Rank other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.BuildingScaleValueRequire != 0) {
        BuildingScaleValueRequire = other.BuildingScaleValueRequire;
      }
      if (other.FacilityValueRequire != 0) {
        FacilityValueRequire = other.FacilityValueRequire;
      }
      if (other.EntrustScoreRequire != 0) {
        EntrustScoreRequire = other.EntrustScoreRequire;
      }
      venturerRankWeight_.Add(other.venturerRankWeight_);
      if (other.EntrustCount != 0) {
        EntrustCount = other.EntrustCount;
      }
      entrustRankWeight_.Add(other.entrustRankWeight_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            BuildingScaleValueRequire = input.ReadInt32();
            break;
          }
          case 32: {
            FacilityValueRequire = input.ReadInt32();
            break;
          }
          case 40: {
            EntrustScoreRequire = input.ReadInt32();
            break;
          }
          case 50: {
            venturerRankWeight_.AddEntriesFrom(input, _map_venturerRankWeight_codec);
            break;
          }
          case 56: {
            EntrustCount = input.ReadInt32();
            break;
          }
          case 66: {
            entrustRankWeight_.AddEntriesFrom(input, _map_entrustRankWeight_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Guild_Rank_Map : pb::IMessage<Guild_Rank_Map> {
    private static readonly pb::MessageParser<Guild_Rank_Map> _parser = new pb::MessageParser<Guild_Rank_Map>(() => new Guild_Rank_Map());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Guild_Rank_Map> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Deploy.GuildRankReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Guild_Rank_Map() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Guild_Rank_Map(Guild_Rank_Map other) : this() {
      items_ = other.items_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Guild_Rank_Map Clone() {
      return new Guild_Rank_Map(this);
    }

    /// <summary>Field number for the "Items" field.</summary>
    public const int ItemsFieldNumber = 1;
    private static readonly pbc::MapField<int, global::Deploy.Guild_Rank>.Codec _map_items_codec
        = new pbc::MapField<int, global::Deploy.Guild_Rank>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Deploy.Guild_Rank.Parser), 10);
    private readonly pbc::MapField<int, global::Deploy.Guild_Rank> items_ = new pbc::MapField<int, global::Deploy.Guild_Rank>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, global::Deploy.Guild_Rank> Items {
      get { return items_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Guild_Rank_Map);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Guild_Rank_Map other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!Items.Equals(other.Items)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= Items.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      items_.WriteTo(output, _map_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += items_.CalculateSize(_map_items_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Guild_Rank_Map other) {
      if (other == null) {
        return;
      }
      items_.Add(other.items_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            items_.AddEntriesFrom(input, _map_items_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
