// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Shop_SubTab.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Deploy {

  /// <summary>Holder for reflection information generated from Shop_SubTab.proto</summary>
  public static partial class ShopSubTabReflection {

    #region Descriptor
    /// <summary>File descriptor for Shop_SubTab.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ShopSubTabReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFTaG9wX1N1YlRhYi5wcm90bxIGZGVwbG95IqABCgtTaG9wX1N1YlRhYhIK",
            "CgJJZBgBIAEoBRIMCgROYW1lGAIgASgFEhQKDFNraW5QYXJ0RW51bRgDIAEo",
            "BRIxCgdBdHRyQWRkGAQgAygLMiAuZGVwbG95LlNob3BfU3ViVGFiLkF0dHJB",
            "ZGRFbnRyeRouCgxBdHRyQWRkRW50cnkSCwoDa2V5GAEgASgFEg0KBXZhbHVl",
            "GAIgASgFOgI4ASKHAQoPU2hvcF9TdWJUYWJfTWFwEjEKBUl0ZW1zGAEgAygL",
            "MiIuZGVwbG95LlNob3BfU3ViVGFiX01hcC5JdGVtc0VudHJ5GkEKCkl0ZW1z",
            "RW50cnkSCwoDa2V5GAEgASgFEiIKBXZhbHVlGAIgASgLMhMuZGVwbG95LlNo",
            "b3BfU3ViVGFiOgI4AWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Deploy.Shop_SubTab), global::Deploy.Shop_SubTab.Parser, new[]{ "Id", "Name", "SkinPartEnum", "AttrAdd" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Deploy.Shop_SubTab_Map), global::Deploy.Shop_SubTab_Map.Parser, new[]{ "Items" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Shop_SubTab : pb::IMessage<Shop_SubTab> {
    private static readonly pb::MessageParser<Shop_SubTab> _parser = new pb::MessageParser<Shop_SubTab>(() => new Shop_SubTab());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Shop_SubTab> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Deploy.ShopSubTabReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Shop_SubTab() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Shop_SubTab(Shop_SubTab other) : this() {
      id_ = other.id_;
      name_ = other.name_;
      skinPartEnum_ = other.skinPartEnum_;
      attrAdd_ = other.attrAdd_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Shop_SubTab Clone() {
      return new Shop_SubTab(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 2;
    private int name_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Name {
      get { return name_; }
      set {
        name_ = value;
      }
    }

    /// <summary>Field number for the "SkinPartEnum" field.</summary>
    public const int SkinPartEnumFieldNumber = 3;
    private int skinPartEnum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SkinPartEnum {
      get { return skinPartEnum_; }
      set {
        skinPartEnum_ = value;
      }
    }

    /// <summary>Field number for the "AttrAdd" field.</summary>
    public const int AttrAddFieldNumber = 4;
    private static readonly pbc::MapField<int, int>.Codec _map_attrAdd_codec
        = new pbc::MapField<int, int>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForInt32(16, 0), 34);
    private readonly pbc::MapField<int, int> attrAdd_ = new pbc::MapField<int, int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, int> AttrAdd {
      get { return attrAdd_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Shop_SubTab);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Shop_SubTab other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (SkinPartEnum != other.SkinPartEnum) return false;
      if (!AttrAdd.Equals(other.AttrAdd)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Name != 0) hash ^= Name.GetHashCode();
      if (SkinPartEnum != 0) hash ^= SkinPartEnum.GetHashCode();
      hash ^= AttrAdd.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Name != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Name);
      }
      if (SkinPartEnum != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(SkinPartEnum);
      }
      attrAdd_.WriteTo(output, _map_attrAdd_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Name != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Name);
      }
      if (SkinPartEnum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SkinPartEnum);
      }
      size += attrAdd_.CalculateSize(_map_attrAdd_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Shop_SubTab other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Name != 0) {
        Name = other.Name;
      }
      if (other.SkinPartEnum != 0) {
        SkinPartEnum = other.SkinPartEnum;
      }
      attrAdd_.Add(other.attrAdd_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Name = input.ReadInt32();
            break;
          }
          case 24: {
            SkinPartEnum = input.ReadInt32();
            break;
          }
          case 34: {
            attrAdd_.AddEntriesFrom(input, _map_attrAdd_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Shop_SubTab_Map : pb::IMessage<Shop_SubTab_Map> {
    private static readonly pb::MessageParser<Shop_SubTab_Map> _parser = new pb::MessageParser<Shop_SubTab_Map>(() => new Shop_SubTab_Map());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Shop_SubTab_Map> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Deploy.ShopSubTabReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Shop_SubTab_Map() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Shop_SubTab_Map(Shop_SubTab_Map other) : this() {
      items_ = other.items_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Shop_SubTab_Map Clone() {
      return new Shop_SubTab_Map(this);
    }

    /// <summary>Field number for the "Items" field.</summary>
    public const int ItemsFieldNumber = 1;
    private static readonly pbc::MapField<int, global::Deploy.Shop_SubTab>.Codec _map_items_codec
        = new pbc::MapField<int, global::Deploy.Shop_SubTab>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Deploy.Shop_SubTab.Parser), 10);
    private readonly pbc::MapField<int, global::Deploy.Shop_SubTab> items_ = new pbc::MapField<int, global::Deploy.Shop_SubTab>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, global::Deploy.Shop_SubTab> Items {
      get { return items_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Shop_SubTab_Map);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Shop_SubTab_Map other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!Items.Equals(other.Items)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= Items.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      items_.WriteTo(output, _map_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += items_.CalculateSize(_map_items_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Shop_SubTab_Map other) {
      if (other == null) {
        return;
      }
      items_.Add(other.items_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            items_.AddEntriesFrom(input, _map_items_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
